spring.application.name=SpringbootDemo
server.port=1205
server.servlet.session.timeout=24h
logging.pattern.console=|%d{HH:mm:ss}| %-5level | %logger{20} | %msg%n
logging.level.root=error
logging.level.win.panyong=info
logging.level.win.panyong.mapper=debug

page.path=classpath:/static/
spring.mvc.view.prefix=/pages/
spring.mvc.view.suffix=.html

jwt.secret=mySecretKey123456789012345678901234567890123456789012345678901234567890
jwt.expiration=86400000

datasource.sqlite.driverClassName=org.sqlite.JDBC
datasource.sqlite.jdbc_url=jdbc:sqlite:/Users/pan/workspaces/localDB.db

datasource.redis.host=basic-node
datasource.redis.port=9736
datasource.redis.password=
datasource.redis.database=10
datasource.redis.timeout=0
datasource.redis.pool.max-wait=-1
datasource.redis.pool.max-idle=8
datasource.redis.pool.min-idle=0

datasource.mysql.jdbc_url=jdbc:mysql://basic-node:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&cachePrepStmts=true&useServerPrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
datasource.mysql.username=root
datasource.mysql.password=a1B2c3D4
datasource.mysql.connection-timeout=10000
datasource.mysql.idle-timeout=600000
datasource.mysql.max-lifetime=1800000
datasource.mysql.minimum-idle=5
datasource.mysql.maximum-pool-size=10
datasource.mysql.max-idle=10
datasource.mysql.max-wait=10000
datasource.mysql.min-idle=5
datasource.mysql.initial-size=5
datasource.mysql.validation-query=SELECT 1
datasource.mysql.test-on-borrow=false
datasource.mysql.test-while-idle=true
datasource.mysql.time-between-eviction-runs-millis=18800

spring.activemq.broker-url=tcp://basic-node:61616
spring.activemq.in-memory=false
spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=5